openapi: 3.1.0
info:
  title: BD2 TPO HTTP API
  summary: Management API
  version: 1.0.0
servers:
- url: localhost:8080
  description: Development Server

paths:
  /client:
    get:
      description: Get
      responses:
        '200':
          description: Clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
  #/client/

components:
  schemas:
    Clients:
      type: object
      required:
      - name
      properties:
        name:
          type: string

