openapi: 3.0.0
info:
  title: API de Gestión de Clientes y Productos
  description: API para realizar operaciones CRUD en clientes y productos.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /clientes:
    get:
      summary: Listar Clientes
      description: Obtiene una lista de todos los clientes.
      responses:
        '200':
          description: Lista de clientes exitosamente recuperada.
          content:
            application/json:
              schema:
                additionalProperties: false
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
    post:
      summary: Crear Cliente
      description: Crea un nuevo cliente.
      requestBody:
        description: Datos del cliente a crear.
        required: true
        content:
          application/json:
            schema:
              additionalProperties: false
              $ref: '#/components/schemas/BaseCliente'
      responses:
        '201':
          description: Cliente creado exitosamente.
          content:
            application/json:
              schema:
                additionalProperties: false
                type: object
                required:
                  - nro_cliente
                properties:
                  nro_cliente:
                    type: integer
        '400':
          description: Solicitud incorrecta
  /clientes/{nro_cliente}:
    parameters:
      - name: nro_cliente
        in: path
        required: true
        description: Número de cliente.
        schema:
          additionalProperties: false
          type: integer
    get:
      summary: Obtener Cliente por ID
      description: Obtiene un cliente por su número de cliente.
      responses:
        '200':
          description: Cliente recuperado exitosamente.
          content:
            application/json:
              schema:
                additionalProperties: false
                $ref: '#/components/schemas/Cliente'
        '404':
          description: Cliente no encontrado.
        '400':
          description: Solicitud incorrecta
    put:
      summary: Actualizar Cliente por ID
      description: Actualiza un cliente existente.
      requestBody:
        description: Datos actualizados del cliente.
        required: true
        content:
          application/json:
            schema:
              additionalProperties: false
              $ref: '#/components/schemas/BaseCliente'
      responses:
        '200':
          description: Cliente actualizado exitosamente.
        '404':
          description: Cliente no encontrado.
        '400':
          description: Solicitud incorrecta
    delete:
      summary: Eliminar Cliente por ID
      description: Elimina un cliente por su número de cliente.
      responses:
        '204':
          description: Cliente eliminado exitosamente.
        '404':
          description: Cliente no encontrado.
        '400':
          description: Solicitud incorrecta
  /productos:
    get:
      summary: Listar Productos
      description: Obtiene una lista de todos los productos.
      responses:
        '200':
          description: Lista de productos exitosamente recuperada.
          content:
            application/json:
              schema:
                additionalProperties: false
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
    post:
      summary: Crear Producto
      description: Crea un nuevo producto.
      requestBody:
        description: Datos del producto a crear.
        required: true
        content:
          application/json:
            schema:
              additionalProperties: false
              $ref: '#/components/schemas/BaseProducto'
      responses:
        '201':
          description: Producto creado exitosamente.
          content:
            application/json:
              schema:
                additionalProperties: false
                type: object
                required:
                  - codigo_producto
                properties:
                  codigo_producto:
                    type: integer
        '400':
          description: Solicitud incorrecta
  /productos/{codigo_producto}:
    parameters:
      - name: codigo_producto
        in: path
        required: true
        description: Código de producto.
        schema:
          additionalProperties: false
          type: integer
    get:
      summary: Obtener Producto por ID
      description: Obtiene un producto por su código de producto.
      responses:
        '200':
          description: Producto recuperado exitosamente.
          content:
            application/json:
              schema:
                additionalProperties: false
                $ref: '#/components/schemas/Producto'
        '404':
          description: Producto no encontrado.
        '400':
          description: Solicitud incorrecta
    put:
      summary: Actualizar Producto por ID
      description: Actualiza un producto existente.
      requestBody:
        description: Datos actualizados del producto.
        required: true
        content:
          application/json:
            schema:
              additionalProperties: false
              $ref: '#/components/schemas/BaseProducto'
      responses:
        '200':
          description: Producto actualizado exitosamente.
        '404':
          description: Producto no encontrado.
        '400':
          description: Solicitud incorrecta
    delete:
      summary: Eliminar Producto por ID
      description: Elimina un producto por su código de producto.
      responses:
        '204':
          description: Producto eliminado exitosamente.
        '404':
          description: Producto no encontrado
        '400':
          description: Solicitud incorrecta
components:
  schemas:
    BaseCliente:
      type: object
      required:
        - nombre
        - apellido
        - direccion
        - activo
        - telefonos
      properties:
        nombre:
          type: string
          example: Alan
        apellido:
          type: string
          example: Martinez
        direccion:
          type: string
          example: Calle 123412
        activo:
          type: integer
          example: 12
        telefonos:
          type: array
          items:
            type: object
            properties:
              tipo:
                type: string
                enum: [F, M]
                example: 'F'
              nro_telefono:
                type: integer
                example: 124141411
              codigo_area:
                type: integer
                example: 135
    Cliente:
      allOf:
        - $ref: '#/components/schemas/BaseCliente'
        - type: object
          required:
            - nro_cliente
          properties:
            nro_cliente:
              type: integer

    BaseProducto:
      type: object
      required:
        - marca
        - nombre
        - descripcion
        - precio
        - stock
      properties:
        marca:
          type: string
          example: Marca de Algo
        nombre:
          type: string
          example: Nombre de Producto
        descripcion:
          type: string
          example: Descripcion del producto
        precio:
          type: number
          example: 124
        stock:
          type: integer
          example: 10
    Producto:
      allOf:
        - $ref: '#/components/schemas/BaseProducto'
        - type: object
          required:
            - codigo_producto
          properties:
            codigo_producto:
              type: integer
